project:
  type: website
  output-dir: docs

website:
  title: "CSC 324"
  navbar:
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Exercises"
        href: exercises/index.qmd
      - text: "Examples"
        href: examples/index.qmd

  sidebar:
    - id: exercises
      title: "Exercises"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - exercises/index.qmd
        - text: "Eloquent Javascript:  Chapter 1"
          href:  exercises/eloquent-ch01.md
        - text: "Eloquent Javascript:  Chapter 2"
          href:  exercises/eloquent-ch02.md
        - text: "Eloquent Javascript:  Chapter 3"
          href:  exercises/eloquent-ch03.md
        - text: "Eloquent Javascript:  Chapter 4"
          href:  exercises/eloquent-ch04.md
        - text: "Eloquent Javascript:  Chapter 5"
          href:  exercises/eloquent-ch05.md
        - text: "Eloquent Javascript:  Chapter 6"
          href:  exercises/eloquent-ch06.md
        - text: "Dr. White's Eloquent JS Solutions"
          href:  exercises/haverbeke-solutions.md
        - text: "Making a Table"
          href:  exercises/table.md
        - text: "Sorting a Table"
          href:  exercises/table-sort.md

    - id: examples
      title: "Examples"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - examples/index.qmd
        - text: "Penguins"
          href:  examples/example_01.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



